#!/usr/bin/env ruby
require 'yaml'
require 'open3'

SERVICES_DIR = "services"

def service_config_file(service_name)
    File.new(File.join(SERVICES_DIR, "#{service_name}.yml"))
end

def load_service_config(services, service_name)
  config = YAML.load(service_config_file(service_name).read) || {}
  config["image"] = service_name 
  services[service_name] = config
 
  dependencies = config["depends_on"]
  if(dependencies && !dependencies.empty?)
    dependencies.each {|dependency_name| load_service_config(services, dependency_name)}
  end
end

def generate_docker_compose_yml(services)
  compose = {
    "version" => "2",
    "services" => services 
  }

  yaml = YAML.dump(compose)

  puts "Final docker-compose yaml:"
  puts yaml
  yaml
end

command = ARGV[0]
service_name = ARGV[1]

services = {}
load_service_config(services, service_name)
compose_config = generate_docker_compose_yml(services)

output, status = Open3.capture2("docker-compose -f - up -d", :stdin_data=> compose_config)
